### PR TITLE
default is "main" branch, not "develop"

### LINKED ISSUE #112: Workflow job "cibuild" step "check-new-links.sh" fails silently
The workflow completes successfully even though one of the jobs fails to perform its task.

Screenshot:
Image

The job outputs error:
```
Run ./script/check-new-links.sh
  ./script/check-new-links.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
fatal: ambiguous argument 'develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I would expect the `cibuild` workflow to enter a failed state, so that we get notified and address the issue.

### PR DESCRIPTION
**Pull request by ericherman**
fixes #112

### CODE REVIEW

**Comment by ericherman** [comment]
Interestingly, this still has a silent failure which I find curious for two reasons:

First, the addition of 'set -o  pipefail' did not cause a failure.

Second, the log shows `fatal: ambiguous argument 'main': unknown revision or path not in the working tree.`

File: script/check-new-links.sh [hunk 1]
```diff
@@ -18,9 +20,11 @@ SKIP_PATTERNS=(
 
 if [ "_${VERBOSE}_" == "__" ]; then VERBOSE=0; fi
 
-for URL in $(git diff develop |
+URLS="$(git diff main |
 		grep '^+' |
-		grep -Eo '(http|https)://[^ )"><]+'); do
+		grep -Eo '(http|https)://[^ )"><]+')"
```
Comment (ixuz) [inline script/check-new-links.sh:25]: > @ixuz [identified](https://github.com/standard-for-public-code/community-implementation-guide-standard/issues/112#issuecomment-2863062050) the for-loop curiously swallowing the error, now it remains to be understood why the checkout doesn't find the `main` branch.

I propose the following adjustment

```suggestion
		grep --extended-regexp --only-matching '(http|https)://[^ )\">\<]+')"
```

With this change, the "check-new-links.sh" script behaves like this:

- When the git diff fails due referencing a non-existant branch, e.g. `"develop"`, then `$ ./script/check-new-links.sh` exits with code 1 (message: `"fatal: ambiguous argument 'develop': unknown revision or path not in the working tree."`)
- Given two valid links in the diff `$ ./script/check-new-links.sh` exits with code 0 (no message output)
- Given two links in the diff, but one is invalid link, then `$ ./script/check-new-links.sh` exits with code 1 (message: `"FAIL: 1 new URLs were not OK"`)
- Given two links in the diff, but both are invalid links, then `$ ./script/check-new-links.sh` exits with code 1 (message: `"FAIL: 2 new URLs were not OK"`)

This should be the correct behavior right? @ericherman

File: script/check-new-links.sh [hunk 2]
```diff
@@ -18,9 +20,11 @@ SKIP_PATTERNS=(
 
 if [ "_${VERBOSE}_" == "__" ]; then VERBOSE=0; fi
```
Comment (ixuz) [inline script/check-new-links.sh:22]: Additionally the `"Run actions/checkout@v4"` step, seems to only shallow fetch the current branch, so `main` is not persent locally. So we may need to add a line like this:

```suggestion
git fetch --depth=1 origin main
```

**Review by ixuz — APPROVED** [review]
Ah yes indeed! It shouldn't block the check if there are no links added or changed in the diff compared to `main`. Yeah this makes sense.

PR looks good to me
